matrix:
  include:
    - language: node_js # backend
      node_js:
        - "6"
      before_script:
        - cd backend
        - npm i
      script:
        - npm run lint
    - language: node_js # frontend
      node_js:
        - "6"
      before_script:
        - cd frontend
        - npm i
      script:
        - npm run build
        - npm run test
    - language: node_js # shared
      node_js:
        - "6"
      before_script:
        - cd shared
        - npm i
      script:
        - npm run lint

notifications:
  email:
    on_success: never
    on_failure: never # change later to always
